### ISSUE TITLE
passing command-line arguments without interactive console

### ISSUE THREAD

**Issue by ghost** [kranzky/megahal#2]
Hello,
would it be possible to use MegaHAL via the command line without the interactive console so it could be wrapped in scripts?
Much thanks in advance.

**Comment by kranzky** [comment]
@Wubix42: you can do that already; have a look at what the command-line does: https://github.com/jasonhutchens/megahal/blob/master/bin/megahal

here's a simple script:

```
#!/usr/bin/env bash

require 'megahal'

megahal = MegaHAL.new
megahal.become(:sherlock)
answer = megahal.reply("Hello Sherlock")
puts answer
```

Here's the API documentation: http://www.rubydoc.info/gems/megahal/MegaHAL#initialize-instance_method
