### ISSUE TITLE
Megahal won't install under Ruby 3.0.0

### ISSUE THREAD

**Issue by redblade7** [kranzky/megahal#5]
Megahal won't install under Ruby 3.0.0. `gem install megahal` fails with:

```
ERROR:  Error installing megahal:
        megahal-2.2.1 requires Ruby version ~> 2.1. The current ruby version is 3.0.0.0.
```

**Comment by kranzky** [comment]
Thanks for the bug report @redblade7 :)

I've just released v2.3.0 which fixes this issue.
